name: diff
description: show diff and post a comment
inputs:
  base:
    description: example input
    required: true
  head:
    description: example input
    required: true
  diff-extra-args:
    description: extra args to git-diff
    required: false
    default: |
      --irreversible-delete
  label:
    description: label(s) to add/remove to indicate diff
    required: false
  comment-header:
    description: header of a comment to post
    required: false
    default: |
      ## diff
  comment-footer:
    description: footer of a comment to post
    required: false
    default: |
      <!-- diff-action -->
  token:
    description: GitHub token to post a comment
    required: true
    default: ${{ github.token }}
outputs:
  different:
    description: true if there is any diff, or false
runs:
  using: 'node16'
  main: 'dist/index.js'
